### ISSUE TITLE
Set NODE_ENV to production

### ISSUE THREAD

**Issue by zeke** [zeke/harp-buildpack#8]
This was attempted near to bottom of the `compile` script, but it doesn't appear to work.

**Comment by edmorley** [comment]
The line mentioned in compile currently does:
`... export NODE_ENV=${NODE_ENV:production}`
(https://github.com/zeke/harp-buildpack/blob/3c6687dae9642166883555a7018215e4401fc343/bin/compile#L58)

I don't believe this is valid bash syntax, according to http://www.tldp.org/LDP/abs/html/parameter-substitution.html it should be:
`... export NODE_ENV=${NODE_ENV:-production}`
(note the extra `-`)

This is what the official nodejs buildpack uses. They also have a nodejs.sh file in the buildpack that gets copied into the profile directory, rather than using an echo statement - I think it's slightly more readable? :-)

See:
https://github.com/heroku/heroku-buildpack-nodejs/blob/b4921004491b01090392ec5c7779a5cd9b824ccc/profile/nodejs.sh#L33
https://github.com/heroku/heroku-buildpack-nodejs/blob/b4921004491b01090392ec5c7779a5cd9b824ccc/lib/environment.sh#L5
https://github.com/heroku/heroku-buildpack-nodejs/blob/b4921004491b01090392ec5c7779a5cd9b824ccc/lib/environment.sh#L13-L18
https://github.com/heroku/heroku-buildpack-nodejs/blob/b4921004491b01090392ec5c7779a5cd9b824ccc/lib/environment.sh#L35-L40

When this is fixed, it would be great if someone could also update:
https://github.com/harp/harpjs.com/blob/7d97994d8463e698b274b3654e7e9f442d4614b8/public/docs/deployment/heroku.md#set-the-production-environment

**Comment by edmorley** [comment]
Ah I see this buildpack is deprecated, I'll submit an issue against the Harp docs (which is how I ended up at this issue) requesting they update them to use the official Heroku nodejs buildpack.

**Comment by zeke** [comment]
Ah thanks for the follow-up @edmorley. Please cc me on that issue/PR if you don't mind. :)

**Comment by edmorley** [comment]
I've opened a PR against their docs (harp/harpjs.com#55). In the meantime, perhaps it would make it easier for people to see this was deprecated if the GitHub repo description mentioned deprecated and linked to http://harpjs.com/docs/deployment/heroku ? Thanks :-)

**Comment by zeke** [comment]
@edmorley done!

**Comment by edmorley** [comment]
Thanks :-)
